name: Generate CV PDF from Markdown

on:
  push:
    branches:
      - gh-pages
    paths:
      - 'CV.md'
      - 'WIP.md'  # This file's changes also trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-plain-generic texlive-lang-european
      
      - name: Convert CV Markdown to PDF
        run: pandoc CV.md -o CV.pdf
      
      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CV.pdf from Markdown changes
          file_pattern: CV.pdf
          branch: gh-pages
